
before_script:
    - git clone -q --depth 1 https://gitlab.com/voxl-public/utilities/ci-tools

include:
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/.build-voxl-emulator.yml'
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/.build-qrb5165-emulator.yml'
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/.deploy-dev.yml'
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/.deploy-dev-deb.yml'
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/.deploy-stable.yml'
  - project: 'voxl-public/utilities/ci-tools'
    file: '/pipeline-configs/.deploy-stable-deb.yml'

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
     - nightly_build_stage
     - build_stage
     - build_stage_qrb5165
     - deploy_stage_dev
     - deploy_stage_dev_deb
     - deploy_stage_stable
     - deploy_stage_stable_deb
