before_script:
    - git clone -q --depth 1 --branch m0054 https://gitlab.com/voxl-public/utilities/ci-tools

include:
  - project: 'voxl-public/utilities/ci-tools'
    ref: m0054
    file: '/pipeline-configs/.nightly-voxl-emulator.yml'
  - project: 'voxl-public/utilities/ci-tools'
    ref: m0054
    file: '/pipeline-configs/.build-voxl-emulator.yml'
  - project: 'voxl-public/utilities/ci-tools'
    ref: m0054
    file: '/pipeline-configs/.deploy-dev.yml'
  - project: 'voxl-public/utilities/ci-tools'
    ref: m0054
    file: '/pipeline-configs/.deploy-stable.yml'
  - project: 'voxl-public/utilities/ci-tools'
    ref: m0054
    file: '/pipeline-configs/.deploy-dev-deb.yml'

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
     - nightly_build_stage
     - build_stage
     - deploy_stage_dev
     - deploy_stage_dev_deb
     - deploy_stage_stable
