#!/bin/sh
################################################################################
# Copyright (c) 2020 ModalAI, Inc. All rights reserved.
#
# author: eric.katzfey@modalai.com
################################################################################

set -e

if [ ! -f /etc/modalai/voxl-streamer.conf ]; then
	echo "INFO: making new /etc/modalai/voxl-streamer.conf"
	cp /share/modalai/voxl-streamer.conf /etc/modalai/voxl-streamer.conf
fi


echo ""
echo "Done installing voxl-streamer"
echo ""
