#!/bin/sh
################################################################################
# Copyright (c) 2022 ModalAI, Inc. All rights reserved.
#
# author: eric.katzfey@modalai.com
################################################################################

set -e

CONF_VERSION=$( cat /usr/share/modalai/voxl-streamer/voxl-streamer.conf | grep "conf-version" )
if [ ! -f /etc/modalai/voxl-streamer.conf ] ||
    ! cat /etc/modalai/voxl-streamer.conf | grep -q "$CONF_VERSION" ; then
	#echo "INFO: making new /etc/modalai/voxl-streamer.conf"
	cp /usr/share/modalai/voxl-streamer/voxl-streamer.conf /etc/modalai/voxl-streamer.conf
fi

