#!/bin/sh
################################################################################
# Copyright (c) 2022 ModalAI, Inc. All rights reserved.
#
# author: eric.katzfey@modalai.com
################################################################################

set -e

# Replace deprecated streamer config file
if [ -f /etc/modalai/voxl-streamer.conf ] && grep -q "version" /etc/modalai/voxl-streamer.conf ; then

    rm /etc/modalai/voxl-streamer.conf
    voxl-configure-streamer

fi

